server:
  port: 8091
spring:
  application:
      name: server91
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuxianshengCn/spring-cloud-conf/
          searchPaths: config-repo
          #username:
          #password: