server:
  port: 8110

logging:
  level:
    root: INFO
    com.secar.trip: DEBUG

spring:
  profiles.active: dev,common_dev
  thymeleaf:
    enabled: true
    cache: false
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.71:3306/test
    username: 123123
    password: 123123
    # 使用druid数据源
    druid:
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  # Redis
  redis:
    host: 192.168.0.71
    port: 6379
    password: wps@2008
    database: 0
  #dubbo服务
  dubbo:
    application:
      name: secar-admin
    registry:
      address: zookeeper://192.168.0.60:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.secar.trip

